<?php
// This is Extensions config
wfLoadExtensions( [	
//     'CategoryTree',	
     'CentralAuth',	
//     'CentralNotice',	
    'CheckUser',	
//     'Cite',	
//     'CiteThisPage',	
//     'ConfirmEdit',	
//     'DismissableSiteNotice',	
//     'Echo',	
//     'EventLogging',	
//     'EventStreamConfig',	
//     'Gadgets',	
//     'ImageMap',	
     'InputBox',	
//     'Interwiki',	
//     'LocalisationUpdate',	
//     'NewUserMessage',	
//     'Nuke',	
//     'OATHAuth',	
//     'PageImages',	
//     'ParserFunctions',	
//     'PdfHandler',	
//     'Poem',	
//     'Scribunto',	
//     'SyntaxHighlight_GeSHi',	
//     'WikiEditor',
] );
